### ISSUE TITLE
Usar GRIP para algoritmo de visión

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/air-hockey#5]
GRIP es un programa que permite diseñar un algoritmo de visión usando bloques, y luego generar código a partir de esos bloques: http://wpilib.screenstepslive.com/s/4485/m/24194/l/463566-introduction-to-grip

**Comment by David-Estevez** [comment]
En la reunión del 20 de Octubre de 2017 [David "el destructor de issues"](https://github.com/davidvelascogarcia), [Jorge](https://github.com/jorgercobo) y [David](https://github.com/David-Estevez) hicieron un primer prototipo de la parte de visión por computador.

Para ello usaron [GRIP](http://wpilib.screenstepslive.com/s/4485/m/24194/l/463566-introduction-to-grip) un programa cojonudo que permite programar algoritmos de visión por computador usando bloques. Una vez terminado, GRIP es capaz de generar automáticamente código en C++, Python o Java que use las librerías [OpenCV](https://opencv.org/).

![](https://s3.amazonaws.com/screensteps_live/image_assets/assets/000/261/102/original/86e23683-8506-46b7-9e41-adbc71413235.png?1481315760)

Con un par de operaciones fuimos capaces de detectar elementos rojos (disco y golpeador) en un ordenador con Windows y exportar el código en Python para luego ejecutarlo en un PC con Linux.

![](https://raw.githubusercontent.com/asrob-uc3m/air-hockey/develop/Computer%20Vision/2017-10-20.png)

Añadiendo un par de operaciones más, fuimos capaces de hacer aparecer círculos que indicasen la localización de los objetos.

![](https://raw.githubusercontent.com/asrob-uc3m/air-hockey/develop/Computer%20Vision/2017-10-20%20(1).png)

Queda por tanto comprobado el potencial de GRIP para prototipar el algoritmo, y creo que @davidvelascogarcia se ha merecido el honor de cerrar esta issue.

**Comment by davidvelascogarcia** [comment]
Muchísimas gracias @David-Estevez , es todo un honor. En vista de haberse finalizado el propósito por  el cual  se abrió esta issue, y estando todos de acuerdo, cierro la misma.
